package me.andannn.aozora.syncer.internal.util

import me.andannn.aozora.core.database.entity.BookEntity
import me.andannn.aozora.syncer.internal.model.BookModel

internal fun BookModel.toEntity() =
    BookEntity(
        bookId = bookId,
        title = title,
        titleKana = titleKana,
        titleSortKana = titleSortKana,
        subtitle = subtitle,
        subtitleKana = subtitleKana,
        originalTitle = originalTitle,
        firstAppearance = firstAppearance,
        categoryNo = categoryNo,
        orthography = orthography,
        workCopyrightFlag = workCopyrightFlag,
        publishDate = publishDate,
        lastUpdateDate = lastUpdateDate,
        cardUrl = cardUrl,
        authorId = authorId,
        authorLastName = authorLastName,
        authorFirstName = authorFirstName,
        authorLastNameKana = authorLastNameKana,
        authorFirstNameKana = authorFirstNameKana,
        authorLastNameSortKana = authorLastNameSortKana,
        authorFirstNameSortKana = authorFirstNameSortKana,
        authorLastNameRomaji = authorLastNameRomaji,
        authorFirstNameRomaji = authorFirstNameRomaji,
        authorRoleFlag = authorRoleFlag,
        authorBirth = authorBirth,
        authorDeath = authorDeath,
        authorCopyrightFlag = authorCopyrightFlag,
        sourceBook1 = sourceBook1,
        sourcePublisher1 = sourcePublisher1,
        sourcePubYear1 = sourcePubYear1,
        inputEdition1 = inputEdition1,
        proofEdition1 = proofEdition1,
        parentSourceBook1 = parentSourceBook1,
        parentSourcePublisher1 = parentSourcePublisher1,
        parentSourcePubYear1 = parentSourcePubYear1,
        sourceBook2 = sourceBook2,
        sourcePublisher2 = sourcePublisher2,
        sourcePubYear2 = sourcePubYear2,
        inputEdition2 = inputEdition2,
        proofEdition2 = proofEdition2,
        parentSourceBook2 = parentSourceBook2,
        parentSourcePublisher2 = parentSourcePublisher2,
        parentSourcePubYear2 = parentSourcePubYear2,
        inputBy = inputBy,
        proofBy = proofBy,
        textFileUrl = textFileUrl,
        textFileLastUpdate = textFileLastUpdate,
        textFileEncoding = textFileEncoding,
        textFileCharset = textFileCharset,
        textFileRevision = textFileRevision,
        htmlFileUrl = htmlFileUrl,
        htmlFileLastUpdate = htmlFileLastUpdate,
        htmlFileEncoding = htmlFileEncoding,
        htmlFileCharset = htmlFileCharset,
        htmlFileRevision = htmlFileRevision,
    )
