/*
 * Copyright 2025, the AozoraBooks project contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package me.andannn.aozora.syncer.internal.model

internal data class BookModel(
    val bookId: String,
    val title: String,
    val titleKana: String,
    val titleSortKana: String?,
    val subtitle: String?,
    val subtitleKana: String?,
    val originalTitle: String?,
    val firstAppearance: String?,
    val categoryNo: String?,
    val orthography: String?,
    val workCopyrightFlag: String?,
    val publishDate: String?,
    val lastUpdateDate: String?,
    val cardUrl: String,
    val authorId: String,
    val authorLastName: String,
    val authorFirstName: String,
    val authorLastNameKana: String?,
    val authorFirstNameKana: String?,
    val authorLastNameSortKana: String?,
    val authorFirstNameSortKana: String?,
    val authorLastNameRomaji: String?,
    val authorFirstNameRomaji: String?,
    val authorRoleFlag: String?,
    val authorBirth: String?,
    val authorDeath: String?,
    val authorCopyrightFlag: String?,
    val sourceBook1: String?,
    val sourcePublisher1: String?,
    val sourcePubYear1: String?,
    val inputEdition1: String?,
    val proofEdition1: String?,
    val parentSourceBook1: String?,
    val parentSourcePublisher1: String?,
    val parentSourcePubYear1: String?,
    val sourceBook2: String?,
    val sourcePublisher2: String?,
    val sourcePubYear2: String?,
    val inputEdition2: String?,
    val proofEdition2: String?,
    val parentSourceBook2: String?,
    val parentSourcePublisher2: String?,
    val parentSourcePubYear2: String?,
    val inputBy: String?,
    val proofBy: String?,
    val textFileUrl: String?,
    val textFileLastUpdate: String?,
    val textFileEncoding: String?,
    val textFileCharset: String?,
    val textFileRevision: String?,
    val htmlFileUrl: String?,
    val htmlFileLastUpdate: String?,
    val htmlFileEncoding: String?,
    val htmlFileCharset: String?,
    val htmlFileRevision: String?,
) {
    constructor(
        csvData: List<String>,
    ) : this(
        bookId = csvData[0],
        title = csvData[1],
        titleKana = csvData[2],
        titleSortKana = csvData[3].ifBlank { null },
        subtitle = csvData[4].ifBlank { null },
        subtitleKana = csvData[5].ifBlank { null },
        originalTitle = csvData[6].ifBlank { null },
        firstAppearance = csvData[7].ifBlank { null },
        categoryNo = csvData[8].ifBlank { null },
        orthography = csvData[9].ifBlank { null },
        workCopyrightFlag = csvData[10].ifBlank { null },
        publishDate = csvData[11].ifBlank { null },
        lastUpdateDate = csvData[12].ifBlank { null },
        cardUrl = csvData[13],
        authorId = csvData[14],
        authorLastName = csvData[15],
        authorFirstName = csvData[16],
        authorLastNameKana = csvData[17].ifBlank { null },
        authorFirstNameKana = csvData[18].ifBlank { null },
        authorLastNameSortKana = csvData[19].ifBlank { null },
        authorFirstNameSortKana = csvData[20].ifBlank { null },
        authorLastNameRomaji = csvData[21].ifBlank { null },
        authorFirstNameRomaji = csvData[22].ifBlank { null },
        authorRoleFlag = csvData[23].ifBlank { null },
        authorBirth = csvData[24].ifBlank { null },
        authorDeath = csvData[25].ifBlank { null },
        authorCopyrightFlag = csvData[26].ifBlank { null },
        sourceBook1 = csvData[27].ifBlank { null },
        sourcePublisher1 = csvData[28].ifBlank { null },
        sourcePubYear1 = csvData[29].ifBlank { null },
        inputEdition1 = csvData[30].ifBlank { null },
        proofEdition1 = csvData[31].ifBlank { null },
        parentSourceBook1 = csvData[32].ifBlank { null },
        parentSourcePublisher1 = csvData[33].ifBlank { null },
        parentSourcePubYear1 = csvData[34].ifBlank { null },
        sourceBook2 = csvData[35].ifBlank { null },
        sourcePublisher2 = csvData[36].ifBlank { null },
        sourcePubYear2 = csvData[37].ifBlank { null },
        inputEdition2 = csvData[38].ifBlank { null },
        proofEdition2 = csvData[39].ifBlank { null },
        parentSourceBook2 = csvData[40].ifBlank { null },
        parentSourcePublisher2 = csvData[41].ifBlank { null },
        parentSourcePubYear2 = csvData[42].ifBlank { null },
        inputBy = csvData[43].ifBlank { null },
        proofBy = csvData[44].ifBlank { null },
        textFileUrl = csvData[45].ifBlank { null },
        textFileLastUpdate = csvData[46].ifBlank { null },
        textFileEncoding = csvData[47].ifBlank { null },
        textFileCharset = csvData[48].ifBlank { null },
        textFileRevision = csvData[49].ifBlank { null },
        htmlFileUrl = csvData[50].ifBlank { null },
        htmlFileLastUpdate = csvData[51].ifBlank { null },
        htmlFileEncoding = csvData[52].ifBlank { null },
        htmlFileCharset = csvData[53].ifBlank { null },
        htmlFileRevision = csvData[54].ifBlank { null },
    )
}
